# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51679dc3371e8740ec3cb67913d08a736074703b111e6bf7ce290f76124c4f843fe758f28ed6fca704f483c395345a9b18c72d46738a70d937433575f10a61df

test:
  secret_key_base: 61544a8d5f54ac690e14a6319d1b893757d8561ba0016cc091872530c4ff966db92b979bf6c154c25f53e283db4ff0742f6730782e0155fda0a26d376752fdfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
